export interface ArtSource {
  label: string;
  href: string;
}

export interface ArtHistoryEntry {
  slug: string;
  canvasId: string;
  title: string;
  artist: string;
  artistYears: string;
  year: string;
  movement: string;
  collection: string;
  publicImage: string;
  publicImageSource: string;
  artistImage: string;
  artistImageSource: string;
  artistImageAlt: string;
  summary: string;
  history: string[];
  lookFor: string[];
  sources: ArtSource[];
}

function commonsImage(fileName: string, width: number): string {
  return `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(fileName)}?width=${width}`;
}

const wikipedia = (slug: string) => `https://en.wikipedia.org/wiki/${slug}`;
const commons = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(fileName)}`;

const portraits = {
  vanGogh: {
    image: commonsImage("Vincent van Gogh - Self-Portrait - Google Art Project.jpg", 700),
    source: commons("Vincent van Gogh - Self-Portrait - Google Art Project.jpg"),
    alt: "Self-portrait of Vincent van Gogh",
  },
  hokusai: {
    image: commonsImage("Portrait of Hokusai by Keisai Eisen.jpg", 700),
    source: commons("Portrait of Hokusai by Keisai Eisen.jpg"),
    alt: "Portrait of Katsushika Hokusai by Keisai Eisen",
  },
  vermeer: {
    image: commonsImage("Johannes Vermeer - The Procuress - Google Art Project.jpg", 700),
    source: commons("Johannes Vermeer - The Procuress - Google Art Project.jpg"),
    alt: "Detail often identified as Johannes Vermeer in The Procuress",
  },
  munch: {
    image: commonsImage("Edvard Munch 1933-2.jpg", 700),
    source: commons("Edvard Munch 1933-2.jpg"),
    alt: "Photograph of Edvard Munch",
  },
  botticelli: {
    image: commonsImage("Sandro Botticelli 083.jpg", 700),
    source: commons("Sandro Botticelli 083.jpg"),
    alt: "Portrait traditionally identified as Sandro Botticelli",
  },
  klimt: {
    image: commonsImage("Gustav Klimt 1914.jpg", 700),
    source: commons("Gustav Klimt 1914.jpg"),
    alt: "Photograph of Gustav Klimt",
  },
  monet: {
    image: commonsImage("Claude Monet 1899 Nadar crop.jpg", 700),
    source: commons("Claude Monet 1899 Nadar crop.jpg"),
    alt: "Photograph of Claude Monet by Nadar",
  },
  michelangelo: {
    image: commonsImage("Michelangelo Daniele da Volterra (dettaglio).jpg", 700),
    source: commons("Michelangelo Daniele da Volterra (dettaglio).jpg"),
    alt: "Portrait of Michelangelo by Daniele da Volterra",
  },
  raphael: {
    image: commonsImage("Raffaello Sanzio.jpg", 700),
    source: commons("Raffaello Sanzio.jpg"),
    alt: "Self-portrait of Raphael",
  },
  bosch: {
    image: commonsImage("Jheronimus Bosch (cropped).jpg", 700),
    source: commons("Jheronimus Bosch (cropped).jpg"),
    alt: "Portrait of Hieronymus Bosch",
  },
  leonardo: {
    image: commonsImage("Francesco Melzi - Portrait of Leonardo - WGA14795.jpg", 700),
    source: commons("Francesco Melzi - Portrait of Leonardo - WGA14795.jpg"),
    alt: "Portrait of Leonardo da Vinci attributed to Francesco Melzi",
  },
  titian: {
    image: commonsImage("Tizian 056.jpg", 700),
    source: commons("Tizian 056.jpg"),
    alt: "Self-portrait of Titian",
  },
  caravaggio: {
    image: commonsImage("Bild-Ottavio Leoni, Caravaggio.jpg", 700),
    source: commons("Bild-Ottavio Leoni, Caravaggio.jpg"),
    alt: "Portrait of Caravaggio by Ottavio Leoni",
  },
  seurat: {
    image: commonsImage("Georges Seurat 1888.jpg", 700),
    source: commons("Georges Seurat 1888.jpg"),
    alt: "Portrait of Georges Seurat",
  },
  renoir: {
    image: commonsImage("Pierre-Auguste Renoir, uncropped image.jpg", 700),
    source: commons("Pierre-Auguste Renoir, uncropped image.jpg"),
    alt: "Photograph of Pierre-Auguste Renoir",
  },
  leighton: {
    image: commonsImage("Frederic Leighton - Self portrait - Google Art Project.jpg", 700),
    source: commons("Frederic Leighton - Self portrait - Google Art Project.jpg"),
    alt: "Self-portrait of Frederic Leighton",
  },
  rembrandt: {
    image: commonsImage("Rembrandt van Rijn - Self-Portrait - Google Art Project.jpg", 700),
    source: commons("Rembrandt van Rijn - Self-Portrait - Google Art Project.jpg"),
    alt: "Self-portrait of Rembrandt van Rijn",
  },
  gentileschi: {
    image: commonsImage("Artemisia Gentileschi - Self-Portrait as the Allegory of Painting - Royal Collection.jpg", 700),
    source: commons("Artemisia Gentileschi - Self-Portrait as the Allegory of Painting - Royal Collection.jpg"),
    alt: "Artemisia Gentileschi as the Allegory of Painting",
  },
  elGreco: {
    image: commonsImage("El Greco - Portrait of an Old Man - WGA10554.jpg", 700),
    source: commons("El Greco - Portrait of an Old Man - WGA10554.jpg"),
    alt: "Portrait often identified as El Greco",
  },
  osman: {
    image: commonsImage("Osman Hamdi Bey.jpg", 700),
    source: commons("Osman Hamdi Bey.jpg"),
    alt: "Photograph of Osman Hamdi Bey",
  },
  goya: {
    image: commonsImage("Francisco de Goya, Autorretrato, 1815.jpg", 700),
    source: commons("Francisco de Goya, Autorretrato, 1815.jpg"),
    alt: "Self-portrait of Francisco Goya",
  },
  copley: {
    image: commonsImage("John Singleton Copley - Self-Portrait - Google Art Project.jpg", 700),
    source: commons("John Singleton Copley - Self-Portrait - Google Art Project.jpg"),
    alt: "Self-portrait of John Singleton Copley",
  },
} as const;

export const ART_HISTORY: ArtHistoryEntry[] = [
  {
    slug: "the-starry-night-vincent-van-gogh",
    canvasId: "vincent-van-gogh-starry-night-1889",
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    artistYears: "1853-1890",
    year: "1889",
    movement: "Post-Impressionism",
    collection: "Museum of Modern Art, New York",
    publicImage: commonsImage("Van Gogh - Starry Night - Google Art Project.jpg", 1800),
    publicImageSource: commons("Van Gogh - Starry Night - Google Art Project.jpg"),
    artistImage: portraits.vanGogh.image,
    artistImageSource: portraits.vanGogh.source,
    artistImageAlt: portraits.vanGogh.alt,
    summary: "A quiet village sits beneath a sky that refuses to stay still. Van Gogh turned a view from Saint-Rémy into one of art's great night scenes.",
    history: [
      "Van Gogh painted this canvas while living at the asylum of Saint-Paul-de-Mausole in Saint-Rémy. The view began with the landscape outside his window. The village and its tall church came from memory and invention.",
      "The painting joined observation with a highly arranged sky. Thick strokes bend around stars, moon and cypress. Van Gogh later called the work an exaggeration, but its force comes from that deliberate push beyond a literal view.",
      "The work passed through the collections of Theo van Gogh and Jo van Gogh-Bonger. MoMA acquired it in 1941. It soon became the museum's best-known painting and a lasting symbol of van Gogh's final years.",
    ],
    lookFor: ["The cypress that links the ground and sky", "Concentric halos around each star", "The calm village beneath the moving heavens"],
    sources: [
      { label: "Museum of Modern Art", href: "https://www.moma.org/collection/works/79802" },
      { label: "Wikipedia", href: wikipedia("The_Starry_Night") },
      { label: "Public-domain image", href: commons("Van Gogh - Starry Night - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-great-wave-off-kanagawa-hokusai",
    canvasId: "katsushika-hokusai-the-great-wave-off-kanagawa-c-1830",
    title: "The Great Wave off Kanagawa",
    artist: "Katsushika Hokusai",
    artistYears: "1760-1849",
    year: "c. 1830-1832",
    movement: "Ukiyo-e",
    collection: "Impressions held by museums worldwide",
    publicImage: commonsImage("The Great Wave off Kanagawa.jpg", 1800),
    publicImageSource: commons("The Great Wave off Kanagawa.jpg"),
    artistImage: portraits.hokusai.image,
    artistImageSource: portraits.hokusai.source,
    artistImageAlt: portraits.hokusai.alt,
    summary: "Three boats face a cresting wall of water while Mount Fuji waits in the distance. Hokusai made danger, work and stillness share one small print.",
    history: [
      "The print opened Hokusai's series Thirty-six Views of Mount Fuji. It was made with carved woodblocks and printed in color. Many impressions were produced, which helped the image travel far beyond Japan.",
      "The wave dominates at first glance. Look again and Mount Fuji repeats its triangular shape in the distance. The fishermen lean into long boats built to carry fresh fish quickly across Edo Bay.",
      "Hokusai used imported Prussian blue, a strong new pigment in Japan. The print later reached Europe and fed the nineteenth-century taste for Japanese art. Its compact design still feels startlingly modern.",
    ],
    lookFor: ["Claw-like tips at the wave's crest", "Mount Fuji framed by the breaking water", "The rowers folded low inside the boats"],
    sources: [
      { label: "The Metropolitan Museum of Art", href: "https://www.metmuseum.org/art/collection/search/45434" },
      { label: "Wikipedia", href: wikipedia("The_Great_Wave_off_Kanagawa") },
      { label: "Public-domain image", href: commons("The Great Wave off Kanagawa.jpg") },
    ],
  },
  {
    slug: "girl-with-a-pearl-earring-johannes-vermeer",
    canvasId: "johannes-vermeer-the-girl-with-the-pearl-earring-c-1665",
    title: "Girl with a Pearl Earring",
    artist: "Johannes Vermeer",
    artistYears: "1632-1675",
    year: "c. 1665",
    movement: "Dutch Golden Age",
    collection: "Mauritshuis, The Hague",
    publicImage: commonsImage("Meisje met de parel.jpg", 1500),
    publicImageSource: commons("Meisje met de parel.jpg"),
    artistImage: portraits.vermeer.image,
    artistImageSource: portraits.vermeer.source,
    artistImageAlt: portraits.vermeer.alt,
    summary: "A young figure turns toward us against a dark field. One bright earring and a half-open mouth make the moment feel unfinished.",
    history: [
      "This is a tronie, not a formal portrait. Dutch artists used tronies to study a face, expression or unusual costume. The sitter's identity was never the point.",
      "Vermeer built the image from broad, clear shapes. The blue and yellow head covering feels exotic rather than documentary. The earring is only a few pale strokes, with no hard outline or visible hook.",
      "The painting entered the Mauritshuis in 1903 after a collector bought it at auction in 1881. Cleaning restored its cool color and direct gaze. Modern research has revealed eyelashes, a green curtain and tiny changes beneath the surface.",
    ],
    lookFor: ["The wet highlight at the corner of the mouth", "Soft edges where the face meets shadow", "The pearl suggested by light rather than detail"],
    sources: [
      { label: "Mauritshuis", href: "https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring" },
      { label: "Wikipedia", href: wikipedia("Girl_with_a_Pearl_Earring") },
      { label: "Public-domain image", href: commons("Meisje met de parel.jpg") },
    ],
  },
  {
    slug: "the-scream-edvard-munch",
    canvasId: "edvard-munch-the-scream-1893",
    title: "The Scream",
    artist: "Edvard Munch",
    artistYears: "1863-1944",
    year: "1893",
    movement: "Expressionism",
    collection: "National Museum, Oslo",
    publicImage: commonsImage("Edvard Munch - The Scream - Google Art Project.jpg", 1500),
    publicImageSource: commons("Edvard Munch - The Scream - Google Art Project.jpg"),
    artistImage: portraits.munch.image,
    artistImageSource: portraits.munch.source,
    artistImageAlt: portraits.munch.alt,
    summary: "A figure stops on a bridge while the landscape seems to cry with it. Munch painted an inner shock as if it had spread through the air.",
    history: [
      "Munch traced the image to a walk near Kristiania, now Oslo. He wrote of a blood-red sky and a great scream passing through nature. The scene became part of his wider Frieze of Life project.",
      "Several versions survive in paint, pastel and print. The National Museum's 1893 painting is the earliest painted version. Its cardboard support and mixed materials add to the raw, exposed effect.",
      "The bridge locks the composition into sharp perspective. Everything beyond it bends and ripples. The central figure is not clearly male or female, which helped it become a broad image of fear rather than one person's story.",
    ],
    lookFor: ["The straight bridge against the fluid landscape", "Two calm walkers in the distance", "Bands of color that echo sound waves"],
    sources: [
      { label: "National Museum of Norway", href: "https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939" },
      { label: "Wikipedia", href: wikipedia("The_Scream") },
      { label: "Public-domain image", href: commons("Edvard Munch - The Scream - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-birth-of-venus-sandro-botticelli",
    canvasId: "sandro-botticelli-the-birth-of-venus-c-1480",
    title: "The Birth of Venus",
    artist: "Sandro Botticelli",
    artistYears: "c. 1445-1510",
    year: "c. 1485",
    movement: "Early Renaissance",
    collection: "Uffizi Galleries, Florence",
    publicImage: commonsImage("Sandro Botticelli - La nascita di Venere - Google Art Project.jpg", 1800),
    publicImageSource: commons("Sandro Botticelli - La nascita di Venere - Google Art Project.jpg"),
    artistImage: portraits.botticelli.image,
    artistImageSource: portraits.botticelli.source,
    artistImageAlt: portraits.botticelli.alt,
    summary: "Venus reaches shore on a shell, pushed by wind and welcomed with a flowered cloak. Botticelli made an ancient myth feel weightless and new.",
    history: [
      "The scene shows Venus arriving on Cyprus after her birth from the sea. Zephyr blows from the left. A figure often identified as Spring waits on shore with a richly patterned mantle.",
      "Botticelli painted on canvas, still an unusual support for a large Florentine work. Gold touches once caught light in Venus's hair. The bodies favor elegant line over strict anatomy.",
      "The exact patron and original setting remain uncertain. The Medici circle and the poetry of Agnolo Poliziano shaped the world around the picture. By the nineteenth century, the work had become a defining image of Renaissance Florence.",
    ],
    lookFor: ["Roses carried on the wind", "The dark outline around each figure", "Tiny gold highlights in Venus's hair"],
    sources: [
      { label: "Uffizi Galleries", href: "https://www.uffizi.it/en/artworks/birth-of-venus" },
      { label: "Wikipedia", href: wikipedia("The_Birth_of_Venus") },
      { label: "Public-domain image", href: commons("Sandro Botticelli - La nascita di Venere - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-kiss-gustav-klimt",
    canvasId: "gustav-klimt-the-kiss-c-1907",
    title: "The Kiss",
    artist: "Gustav Klimt",
    artistYears: "1862-1918",
    year: "1908-1909",
    movement: "Vienna Secession",
    collection: "Upper Belvedere, Vienna",
    publicImage: commonsImage("The Kiss - Gustav Klimt - Google Cultural Institute.jpg", 1500),
    publicImageSource: commons("The Kiss - Gustav Klimt - Google Cultural Institute.jpg"),
    artistImage: portraits.klimt.image,
    artistImageSource: portraits.klimt.source,
    artistImageAlt: portraits.klimt.alt,
    summary: "Two figures meet inside a field of gold and pattern. Their bodies almost vanish into the decorated surface around them.",
    history: [
      "Klimt made The Kiss near the end of his golden phase. He had studied Byzantine mosaics in Ravenna and used gold leaf to collapse the space between painting, icon and ornament.",
      "The Belvedere bought the work in 1908 before Klimt had fully completed it. That quick purchase was a sharp change from the public battles that surrounded some of his earlier commissions.",
      "Squares and hard edges cover the man's robe. Circles and flowers soften the woman's dress. The couple kneels at the edge of a flowered ledge, which gives the embrace a quiet sense of risk.",
    ],
    lookFor: ["Gold leaf that changes with the light", "Different patterns assigned to each figure", "The narrow edge beneath the woman's feet"],
    sources: [
      { label: "Belvedere Museum", href: "https://www.belvedere.at/en/press/klimt-collection-belvedere" },
      { label: "Wikipedia", href: wikipedia("The_Kiss_(Klimt)") },
      { label: "Public-domain image", href: commons("The Kiss - Gustav Klimt - Google Cultural Institute.jpg") },
    ],
  },
  {
    slug: "water-lilies-claude-monet",
    canvasId: "claude-monet-water-lilies-1916",
    title: "Water Lilies",
    artist: "Claude Monet",
    artistYears: "1840-1926",
    year: "1916",
    movement: "Impressionism",
    collection: "One of Monet's late water-lily paintings",
    publicImage: commonsImage("Claude Monet - Water Lilies - Google Art Project.jpg", 1600),
    publicImageSource: commons("Claude Monet - Water Lilies - Google Art Project.jpg"),
    artistImage: portraits.monet.image,
    artistImageSource: portraits.monet.source,
    artistImageAlt: portraits.monet.alt,
    summary: "Monet removed the horizon and let a pond fill the whole canvas. Water, reflection and paint become hard to separate.",
    history: [
      "Monet created a water garden at Giverny and painted it for more than two decades. The pond was not a wild scene. He shaped it carefully with imported lilies, a bridge and controlled planting.",
      "His late canvases grew larger as his sight weakened and Europe went through war. Reflections break the normal sense of depth. A patch may read as water, cloud or bare paint depending on where you stand.",
      "The series ended in the great decorative panels now at the Musée de l'Orangerie. These works gave later abstract painters a model for large, immersive fields of color.",
    ],
    lookFor: ["Reflections with no visible horizon", "Thick flowers over thin pools of color", "Open passages where canvas nearly shows through"],
    sources: [
      { label: "Art Institute of Chicago", href: "https://www.artic.edu/artworks/16568/water-lilies" },
      { label: "Wikipedia", href: wikipedia("Water_Lilies_(Monet_series)") },
      { label: "Public-domain image", href: commons("Claude Monet - Water Lilies - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-creation-of-adam-michelangelo",
    canvasId: "michelangelo-the-creation-of-adam-1512",
    title: "The Creation of Adam",
    artist: "Michelangelo",
    artistYears: "1475-1564",
    year: "c. 1512",
    movement: "High Renaissance",
    collection: "Sistine Chapel, Vatican City",
    publicImage: commonsImage("Michelangelo - Creation of Adam (cropped).jpg", 1800),
    publicImageSource: commons("Michelangelo - Creation of Adam (cropped).jpg"),
    artistImage: portraits.michelangelo.image,
    artistImageSource: portraits.michelangelo.source,
    artistImageAlt: portraits.michelangelo.alt,
    summary: "Two hands almost touch. Michelangelo turned the creation of humanity into a gap charged with movement.",
    history: [
      "The fresco belongs to the central sequence on the Sistine Chapel ceiling. Michelangelo painted the vast ceiling between 1508 and 1512, working on wet plaster in sections.",
      "Adam rests heavily on the earth. God moves toward him inside a rushing group of figures and cloth. Their nearly touching fingers hold the instant before life passes between them.",
      "The image became famous far beyond its chapel setting. Restoration completed in 1994 removed centuries of soot and glue, revealing a much brighter range of pink, green and blue.",
    ],
    lookFor: ["The small charged space between two fingers", "Adam's body echoing God's pose", "The sweeping mantle that carries the heavenly group"],
    sources: [
      { label: "Vatican Museums", href: "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/cappella-sistina/volta/storie-centrali/creazione-di-adamo.html" },
      { label: "Wikipedia", href: wikipedia("The_Creation_of_Adam") },
      { label: "Public-domain image", href: commons("Michelangelo - Creation of Adam (cropped).jpg") },
    ],
  },
  {
    slug: "the-school-of-athens-raphael",
    canvasId: "raphael-the-school-of-athens-1509",
    title: "The School of Athens",
    artist: "Raphael",
    artistYears: "1483-1520",
    year: "1509-1511",
    movement: "High Renaissance",
    collection: "Apostolic Palace, Vatican City",
    publicImage: commonsImage("The School of Athens by Raffaello Sanzio da Urbino.jpg", 1800),
    publicImageSource: commons("The School of Athens by Raffaello Sanzio da Urbino.jpg"),
    artistImage: portraits.raphael.image,
    artistImageSource: portraits.raphael.source,
    artistImageAlt: portraits.raphael.alt,
    summary: "Ancient thinkers gather inside an ideal building. Raphael made philosophy look like a lively public event.",
    history: [
      "Pope Julius II asked Raphael to decorate rooms in the Vatican. This fresco faces a scene of theology, setting reason and faith in a carefully balanced program.",
      "Plato and Aristotle walk at the center. Plato points upward toward ideal forms. Aristotle extends his hand toward the material world. Around them, groups argue, calculate, read and listen.",
      "Raphael used single-point perspective to pull every line toward the central pair. He also gave several ancient figures the faces of Renaissance artists, including a brooding Michelangelo as Heraclitus.",
    ],
    lookFor: ["Perspective lines aimed at Plato and Aristotle", "Raphael's own face at the far right", "Michelangelo's features on the seated Heraclitus"],
    sources: [
      { label: "Vatican Museums", href: "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/stanze-di-raffaello/stanza-della-segnatura/scuola-di-atene.html" },
      { label: "Wikipedia", href: wikipedia("The_School_of_Athens") },
      { label: "Public-domain image", href: commons("The School of Athens by Raffaello Sanzio da Urbino.jpg") },
    ],
  },
  {
    slug: "the-garden-of-earthly-delights-hieronymus-bosch",
    canvasId: "hieronymus-bosch-the-garden-of-earthly-delights",
    title: "The Garden of Earthly Delights",
    artist: "Hieronymus Bosch",
    artistYears: "c. 1450-1516",
    year: "c. 1490-1500",
    movement: "Northern Renaissance",
    collection: "Museo Nacional del Prado, Madrid",
    publicImage: commonsImage("The Garden of Earthly Delights by Bosch High Resolution.jpg", 1800),
    publicImageSource: commons("The Garden of Earthly Delights by Bosch High Resolution.jpg"),
    artistImage: portraits.bosch.image,
    artistImageSource: portraits.bosch.source,
    artistImageAlt: portraits.bosch.alt,
    summary: "Paradise, earthly pleasure and punishment unfold across three crowded panels. Bosch packed a moral puzzle with details that still resist a single answer.",
    history: [
      "The triptych moves from Eden on the left to a crowded central garden and a dark hell on the right. When closed, its outer panels show the world inside a transparent sphere.",
      "Bosch mixed familiar religious subjects with invented animals, giant fruit and impossible machines. The work was probably made for a courtly audience that could study and debate its strange details at close range.",
      "The painting entered the Spanish royal collection in the sixteenth century and later moved to the Prado. Its meaning remains disputed. Warning, satire and fascination all occupy the same surface.",
    ],
    lookFor: ["The owl hidden in the Eden panel", "Fragile fruit larger than people", "Musical instruments turned into tools of punishment"],
    sources: [
      { label: "Museo Nacional del Prado", href: "https://www.museodelprado.es/en/the-collection/art-work/the-garden-of-earthly-delights-triptych/02388242-6d6a-4e9e-a992-e1311eab3609" },
      { label: "Wikipedia", href: wikipedia("The_Garden_of_Earthly_Delights") },
      { label: "Public-domain image", href: commons("The Garden of Earthly Delights by Bosch High Resolution.jpg") },
    ],
  },
  {
    slug: "lady-with-an-ermine-leonardo-da-vinci",
    canvasId: "leonardo-da-vinci-the-lady-with-an-ermine-1489",
    title: "Lady with an Ermine",
    artist: "Leonardo da Vinci",
    artistYears: "1452-1519",
    year: "c. 1489-1490",
    movement: "High Renaissance",
    collection: "National Museum in Kraków",
    publicImage: commonsImage("Leonardo da Vinci - Lady with an Ermine - WGA12698.jpg", 1500),
    publicImageSource: commons("Leonardo da Vinci - Lady with an Ermine - WGA12698.jpg"),
    artistImage: portraits.leonardo.image,
    artistImageSource: portraits.leonardo.source,
    artistImageAlt: portraits.leonardo.alt,
    summary: "Cecilia Gallerani turns as if someone has just entered the room. The animal in her arms turns with her.",
    history: [
      "Leonardo painted Cecilia while working at the Milanese court of Ludovico Sforza. She was educated, wrote poetry and was Ludovico's young mistress.",
      "The ermine may carry several meanings. It was linked with purity, with Ludovico's emblem and with a play on Cecilia's surname. Leonardo joined the animal and sitter through matching turns and long, alert hands.",
      "The portrait was bought in Italy by Prince Adam Jerzy Czartoryski around 1800. It survived repeated wartime moves and Nazi seizure. It is now the only Leonardo painting in a Polish collection.",
    ],
    lookFor: ["The shared turn of sitter and animal", "Leonardo's careful study of the hand", "Soft light modeling the face against darkness"],
    sources: [
      { label: "National Museum in Kraków", href: "https://mnk.pl/en/collections/lady-with-an-ermine/" },
      { label: "Wikipedia", href: wikipedia("Lady_with_an_Ermine") },
      { label: "Public-domain image", href: commons("Leonardo da Vinci - Lady with an Ermine - WGA12698.jpg") },
    ],
  },
  {
    slug: "bacchus-and-ariadne-titian",
    canvasId: "titian-bacchus-and-ariadne-1522",
    title: "Bacchus and Ariadne",
    artist: "Titian",
    artistYears: "c. 1488-1576",
    year: "1520-1523",
    movement: "Venetian Renaissance",
    collection: "The National Gallery, London",
    publicImage: commonsImage("Titian - Bacchus and Ariadne - National Gallery, London.jpg", 1800),
    publicImageSource: commons("Titian - Bacchus and Ariadne - National Gallery, London.jpg"),
    artistImage: portraits.titian.image,
    artistImageSource: portraits.titian.source,
    artistImageAlt: portraits.titian.alt,
    summary: "Bacchus leaps from his chariot at the sight of Ariadne. Titian freezes love at first sight in a burst of blue, red and motion.",
    history: [
      "The painting was made for Alfonso I d'Este's private suite in Ferrara. It belonged to a series of mythological scenes designed for close, learned viewing.",
      "Ariadne has been abandoned by Theseus, whose ship appears at the far left. Bacchus arrives with a noisy group of followers and promises her a place among the stars.",
      "Titian used some of the strongest pigments then available. Ultramarine fills the sky. Bacchus's red drapery cuts across it while his body hangs in midair, an unusually bold pose for the period.",
    ],
    lookFor: ["Theseus's tiny ship leaving the island", "Ariadne's crown becoming a constellation", "The cheetahs pulling Bacchus's chariot"],
    sources: [
      { label: "The National Gallery", href: "https://www.nationalgallery.org.uk/paintings/titian-bacchus-and-ariadne" },
      { label: "Wikipedia", href: wikipedia("Bacchus_and_Ariadne") },
      { label: "Public-domain image", href: commons("Titian - Bacchus and Ariadne - National Gallery, London.jpg") },
    ],
  },
  {
    slug: "the-cardsharps-caravaggio",
    canvasId: "michelangelo-caravaggio-cardsharps-1594",
    title: "The Cardsharps",
    artist: "Caravaggio",
    artistYears: "1571-1610",
    year: "c. 1595",
    movement: "Baroque",
    collection: "Kimbell Art Museum, Fort Worth",
    publicImage: commonsImage("Michelangelo Caravaggio 060.jpg", 1700),
    publicImageSource: commons("Michelangelo Caravaggio 060.jpg"),
    artistImage: portraits.caravaggio.image,
    artistImageSource: portraits.caravaggio.source,
    artistImageAlt: portraits.caravaggio.alt,
    summary: "A well-dressed young player studies his cards while two cheats work around him. Caravaggio makes the trick obvious to us and invisible to its target.",
    history: [
      "Caravaggio painted this early in his Roman career. The scene helped establish his reputation and attracted the patronage of Cardinal Francesco Maria del Monte.",
      "The older cheat signals the victim's cards through a torn glove. His partner reaches behind his back for a hidden card. Every costume detail supports the deception.",
      "The Kimbell painting was rediscovered in 1987 after its authorship had been forgotten. Technical study and documentary evidence supported its acceptance as Caravaggio's original composition.",
    ],
    lookFor: ["The accomplice's split glove", "Extra cards tucked behind the young cheat", "The victim's open, unguarded posture"],
    sources: [
      { label: "Kimbell Art Museum", href: "https://kimbellart.org/collection/ap-198706" },
      { label: "Wikipedia", href: wikipedia("The_Cardsharps") },
      { label: "Public-domain image", href: commons("Michelangelo Caravaggio 060.jpg") },
    ],
  },
  {
    slug: "a-sunday-on-la-grande-jatte-georges-seurat",
    canvasId: "georges-seurat-a-sunday-afternoon-on-the-island-of-la-grande-jatte-c-1884",
    title: "A Sunday on La Grande Jatte",
    artist: "Georges Seurat",
    artistYears: "1859-1891",
    year: "1884-1886",
    movement: "Neo-Impressionism",
    collection: "Art Institute of Chicago",
    publicImage: commonsImage("Georges Seurat - A Sunday on La Grande Jatte -- 1884 - Google Art Project.jpg", 1800),
    publicImageSource: commons("Georges Seurat - A Sunday on La Grande Jatte -- 1884 - Google Art Project.jpg"),
    artistImage: portraits.seurat.image,
    artistImageSource: portraits.seurat.source,
    artistImageAlt: portraits.seurat.alt,
    summary: "Parisians gather beside the Seine, but no one quite touches. Seurat built a modern crowd from countless small marks and strict geometry.",
    history: [
      "Seurat worked on the ten-foot-wide canvas for about two years. He made many drawings and painted studies on the island before assembling the final scene in his studio.",
      "Small touches of contrasting color mix in the viewer's eye. The method became known as Pointillism, though Seurat preferred language that stressed color division and optical theory.",
      "The painting appeared at the final Impressionist exhibition in 1886 and pointed toward Neo-Impressionism. Its people are modern and fashionable, yet their stillness makes the sunny park feel formal and strange.",
    ],
    lookFor: ["The monkey on a lead at lower right", "A painted border that repeats the scene's colors", "Sails and umbrellas built from simple triangles"],
    sources: [
      { label: "Art Institute of Chicago", href: "https://www.artic.edu/artworks/27992/a-sunday-on-la-grande-jatte-1884" },
      { label: "Wikipedia", href: wikipedia("A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte") },
      { label: "Public-domain image", href: commons("Georges Seurat - A Sunday on La Grande Jatte -- 1884 - Google Art Project.jpg") },
    ],
  },
  {
    slug: "woman-with-a-parasol-claude-monet",
    canvasId: "claude-monet-lady-with-a-parasol-1875",
    title: "Woman with a Parasol",
    artist: "Claude Monet",
    artistYears: "1840-1926",
    year: "1875",
    movement: "Impressionism",
    collection: "National Gallery of Art, Washington",
    publicImage: commonsImage("Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg", 1500),
    publicImageSource: commons("Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg"),
    artistImage: portraits.monet.image,
    artistImageSource: portraits.monet.source,
    artistImageAlt: portraits.monet.alt,
    summary: "Camille Monet turns on a windy hill with her son behind her. Fast brushwork makes the air itself part of the portrait.",
    history: [
      "Monet painted his wife Camille and their son Jean outdoors at Argenteuil. The low viewpoint lifts Camille against the sky and gives a casual family walk unusual scale.",
      "The canvas was completed quickly, probably in one sitting. Exposed ground and loose strokes preserve that speed. The veil, grass and clouds all move in the same gust.",
      "Monet showed the painting at the second Impressionist exhibition in 1876. It joined a portrait-like figure with the movement and changing light that drove his landscape work.",
    ],
    lookFor: ["The green underside of the parasol", "A veil that almost dissolves into the sky", "Jean appearing just over the ridge"],
    sources: [
      { label: "National Gallery of Art", href: "https://www.nga.gov/artworks/61379-woman-parasol-madame-monet-and-her-son" },
      { label: "Wikipedia", href: wikipedia("Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son") },
      { label: "Public-domain image", href: commons("Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg") },
    ],
  },
  {
    slug: "luncheon-of-the-boating-party-renoir",
    canvasId: "renoir-luncheon-of-the-boating-party-1880-1881",
    title: "Luncheon of the Boating Party",
    artist: "Pierre-Auguste Renoir",
    artistYears: "1841-1919",
    year: "1880-1881",
    movement: "Impressionism",
    collection: "The Phillips Collection, Washington",
    publicImage: commonsImage("Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg", 1800),
    publicImageSource: commons("Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg"),
    artistImage: portraits.renoir.image,
    artistImageSource: portraits.renoir.source,
    artistImageAlt: portraits.renoir.alt,
    summary: "Friends linger over lunch on a balcony above the Seine. Renoir turned a social afternoon into a carefully revised monument to modern leisure.",
    history: [
      "The setting is the Maison Fournaise at Chatou, a restaurant popular with boaters. Renoir used friends, models and future wife Aline Charigot for the large group.",
      "The relaxed scene took months of planning and revision. Technical study shows that Renoir moved figures and added the striped awning after painting more of the open landscape.",
      "Collector Duncan Phillips bought the painting in 1923. It became the anchor of his young museum and remains the best-known work in the Phillips Collection.",
    ],
    lookFor: ["Aline Charigot playing with a small dog", "Gustave Caillebotte seated backward on a chair", "Red accents moving across hats, fruit and clothing"],
    sources: [
      { label: "The Phillips Collection", href: "https://www.phillipscollection.org/collection/luncheon-boating-party" },
      { label: "Wikipedia", href: wikipedia("Luncheon_of_the_Boating_Party") },
      { label: "Public-domain image", href: commons("Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg") },
    ],
  },
  {
    slug: "flaming-june-frederic-leighton",
    canvasId: "frederic-leighton-flaming-june-1895",
    title: "Flaming June",
    artist: "Frederic Leighton",
    artistYears: "1830-1896",
    year: "1895",
    movement: "Victorian Aestheticism",
    collection: "Museo de Arte de Ponce",
    publicImage: commonsImage("Frederic Leighton - Flaming June - Google Art Project.jpg", 1500),
    publicImageSource: commons("Frederic Leighton - Flaming June - Google Art Project.jpg"),
    artistImage: portraits.leighton.image,
    artistImageSource: portraits.leighton.source,
    artistImageAlt: portraits.leighton.alt,
    summary: "A sleeping figure curls into a near-perfect circle of orange cloth. Leighton made heat and stillness feel almost solid.",
    history: [
      "Leighton painted Flaming June near the end of his life. Its square format and tightly folded pose turn a resting woman into a study of line, color and enclosed form.",
      "The oleander at upper right may hint at danger because the plant is poisonous. The setting remains uncertain. It could be a terrace, a dream or a personification of summer itself.",
      "The painting disappeared from broad public view for decades. Luis A. Ferré bought it in 1963 for the museum he founded in Puerto Rico. Its reputation rose sharply after later exhibitions.",
    ],
    lookFor: ["The nearly circular body and drapery", "A narrow strip of bright sea", "The poisonous oleander branch"],
    sources: [
      { label: "Museo de Arte de Ponce", href: "https://emuseum.museoarteponce.org/objects/3669/flaming-june" },
      { label: "Wikipedia", href: wikipedia("Flaming_June") },
      { label: "Public-domain image", href: commons("Frederic Leighton - Flaming June - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-storm-on-the-sea-of-galilee-rembrandt",
    canvasId: "rembrandt-van-rijn-the-storm-on-the-sea-of-galilee-1633",
    title: "The Storm on the Sea of Galilee",
    artist: "Rembrandt van Rijn",
    artistYears: "1606-1669",
    year: "1633",
    movement: "Dutch Baroque",
    collection: "Isabella Stewart Gardner Museum, missing since 1990",
    publicImage: commonsImage("Rembrandt Christ in the Storm on the Lake of Galilee.jpg", 1500),
    publicImageSource: commons("Rembrandt Christ in the Storm on the Lake of Galilee.jpg"),
    artistImage: portraits.rembrandt.image,
    artistImageSource: portraits.rembrandt.source,
    artistImageAlt: portraits.rembrandt.alt,
    summary: "A small boat tilts into a wall of water while its passengers struggle in every direction. Calm sits at the center of the panic.",
    history: [
      "This is Rembrandt's only known painted seascape. He based it on the Gospel story in which Christ calms a storm as his disciples fear the boat will sink.",
      "A bright wave hits the left side while the right falls into shadow. Each figure reacts differently. One sailor looks out toward us and is often identified as Rembrandt himself.",
      "The painting was stolen from the Gardner Museum on March 18, 1990, with twelve other works. Its empty frame still hangs in the Dutch Room under the terms of Isabella Gardner's will.",
    ],
    lookFor: ["Rembrandt looking out from the boat", "The snapped rigging against bright spray", "Christ remaining calm in the shadows"],
    sources: [
      { label: "Isabella Stewart Gardner Museum", href: "https://www.gardnermuseum.org/experience/collection/10953" },
      { label: "Wikipedia", href: wikipedia("The_Storm_on_the_Sea_of_Galilee") },
      { label: "Public-domain image", href: commons("Rembrandt Christ in the Storm on the Lake of Galilee.jpg") },
    ],
  },
  {
    slug: "judith-beheading-holofernes-artemisia-gentileschi",
    canvasId: "artemisia-gentileschi-judith-beheading-holofernes-1620",
    title: "Judith Beheading Holofernes",
    artist: "Artemisia Gentileschi",
    artistYears: "1593-c. 1654",
    year: "c. 1620",
    movement: "Baroque",
    collection: "Uffizi Galleries, Florence",
    publicImage: commonsImage("Artemisia Gentileschi - Judith Beheading Holofernes - Google Art Project.jpg", 1600),
    publicImageSource: commons("Artemisia Gentileschi - Judith Beheading Holofernes - Google Art Project.jpg"),
    artistImage: portraits.gentileschi.image,
    artistImageSource: portraits.gentileschi.source,
    artistImageAlt: portraits.gentileschi.alt,
    summary: "Judith and her maid work together with physical force. Gentileschi pushed a familiar biblical scene close to the viewer and refused to soften it.",
    history: [
      "The story comes from the Book of Judith. Judith enters the enemy camp, gets the general Holofernes drunk and kills him to save her city.",
      "Gentileschi followed Caravaggio's dramatic light and close staging, but made Judith and Abra active partners. Their sleeves are rolled back. Their arms form a strong crossing structure over the bed.",
      "The painting was likely completed after Gentileschi returned to Rome from Florence. It entered the Medici collection and was later displayed at the Uffizi, where its authorship and force gained new attention in the twentieth century.",
    ],
    lookFor: ["The crossing diagonals of four arms", "Judith's carefully protected dress", "Light concentrated on the three faces"],
    sources: [
      { label: "Uffizi Galleries", href: "https://www.uffizi.it/en/artworks/judith-beheading-holofernes" },
      { label: "Wikipedia", href: wikipedia("Judith_Slaying_Holofernes_(Artemisia_Gentileschi,_Florence)") },
      { label: "Public-domain image", href: commons("Artemisia Gentileschi - Judith Beheading Holofernes - Google Art Project.jpg") },
    ],
  },
  {
    slug: "view-of-toledo-el-greco",
    canvasId: "el-greco-view-of-toledo-1600",
    title: "View of Toledo",
    artist: "El Greco",
    artistYears: "1541-1614",
    year: "c. 1599-1600",
    movement: "Spanish Renaissance",
    collection: "The Metropolitan Museum of Art, New York",
    publicImage: commonsImage("View of Toledo MET DT1502.jpg", 1500),
    publicImageSource: commons("View of Toledo MET DT1502.jpg"),
    artistImage: portraits.elGreco.image,
    artistImageSource: portraits.elGreco.source,
    artistImageAlt: portraits.elGreco.alt,
    summary: "Toledo rises beneath a green-black storm. El Greco rearranged the city to make a portrait of atmosphere rather than a street map.",
    history: [
      "Independent landscapes were rare in Spanish painting around 1600. El Greco made one of the period's most charged examples in the city where he had built his career.",
      "The skyline is recognizable but altered. El Greco shifted buildings to create a stronger rhythm and separated the cathedral from the Alcázar. Light breaks across the ground in irregular patches.",
      "The painting's long history before the nineteenth century is unclear. Modern artists and writers admired its stretched forms and emotional color, which seemed to anticipate Expressionism.",
    ],
    lookFor: ["Pale buildings under a nearly black cloud", "The city moved for visual effect", "Electric green cutting through the foreground"],
    sources: [
      { label: "The Metropolitan Museum of Art", href: "https://www.metmuseum.org/art/collection/search/436575" },
      { label: "Wikipedia", href: wikipedia("View_of_Toledo") },
      { label: "Public-domain image", href: commons("View of Toledo MET DT1502.jpg") },
    ],
  },
  {
    slug: "the-tortoise-trainer-osman-hamdi-bey",
    canvasId: "osman-hamdi-the-tortoise-trainer-1906",
    title: "The Tortoise Trainer",
    artist: "Osman Hamdi Bey",
    artistYears: "1842-1910",
    year: "1906",
    movement: "Ottoman Academic painting",
    collection: "Pera Museum, Istanbul",
    publicImage: commonsImage("The Tortoise Trainer - Osman Hamdi Bey.jpg", 1500),
    publicImageSource: commons("The Tortoise Trainer - Osman Hamdi Bey.jpg"),
    artistImage: portraits.osman.image,
    artistImageSource: portraits.osman.source,
    artistImageAlt: portraits.osman.alt,
    summary: "An elderly man bends toward a group of tortoises in a worn tiled room. The strange lesson has become a durable image of slow reform.",
    history: [
      "Osman Hamdi Bey was a painter, archaeologist and museum director. He often used himself as a model and built scenes from studied costumes, architecture and objects.",
      "The trainer carries a small drum and flute while the tortoises gather around leaves on the floor. The exact meaning is open, but the picture is often read as a satire on difficult, slow-moving institutions.",
      "The work appeared at the Paris Salon in 1906 under a French title meaning The Man with Tortoises. It is now one of the most recognized paintings in Turkey.",
    ],
    lookFor: ["Damaged tilework in the Green Mosque setting", "Musical instruments tucked behind the trainer", "Leaves used as both food and teaching aid"],
    sources: [
      { label: "Pera Museum", href: "https://www.peramuseum.org/artwork/the-tortoise-trainer/15/92" },
      { label: "Wikipedia", href: wikipedia("The_Tortoise_Trainer") },
      { label: "Public-domain image", href: commons("The Tortoise Trainer - Osman Hamdi Bey.jpg") },
    ],
  },
  {
    slug: "the-parasol-francisco-goya",
    canvasId: "francisco-goya-the-parasol-1777",
    title: "The Parasol",
    artist: "Francisco Goya",
    artistYears: "1746-1828",
    year: "1777",
    movement: "Rococo",
    collection: "Museo Nacional del Prado, Madrid",
    publicImage: commonsImage("El Quitasol (Goya).jpg", 1700),
    publicImageSource: commons("El Quitasol (Goya).jpg"),
    artistImage: portraits.goya.image,
    artistImageSource: portraits.goya.source,
    artistImageAlt: portraits.goya.alt,
    summary: "A young man shades a seated woman on a bright day. The scene looks casual, but it was designed for a royal dining room wall.",
    history: [
      "Goya made The Parasol as a full-size cartoon for a tapestry. The finished textile was intended for the dining room of the future Charles IV and María Luisa of Parma at El Pardo.",
      "The pair wear fashionable clothing associated with Madrid's majos and majas. A low viewpoint and strong diagonal parasol suit the painting's planned position high on a wall.",
      "The tapestry project gave Goya steady royal work and practice with scenes of modern life. Its easy charm sits far from the darker court pictures and war images he made later.",
    ],
    lookFor: ["The parasol making a strong green diagonal", "A small dog curled in the foreground", "Sunlight modeled for translation into wool and silk"],
    sources: [
      { label: "Museo Nacional del Prado", href: "https://www.museodelprado.es/en/the-collection/art-work/the-parasol/a230a80f-a899-4535-9e90-ad883bd096c5" },
      { label: "Wikipedia", href: wikipedia("The_Parasol") },
      { label: "Public-domain image", href: commons("El Quitasol (Goya).jpg") },
    ],
  },
  {
    slug: "watson-and-the-shark-john-singleton-copley",
    canvasId: "john-copley-watson-and-the-shark-1778",
    title: "Watson and the Shark",
    artist: "John Singleton Copley",
    artistYears: "1738-1815",
    year: "1778",
    movement: "History painting",
    collection: "National Gallery of Art, Washington",
    publicImage: commonsImage("John Singleton Copley - Watson and the Shark - Google Art Project.jpg", 1800),
    publicImageSource: commons("John Singleton Copley - Watson and the Shark - Google Art Project.jpg"),
    artistImage: portraits.copley.image,
    artistImageSource: portraits.copley.source,
    artistImageAlt: portraits.copley.alt,
    summary: "A rescue stalls at the most dangerous instant. Copley made a recent event look as grand and urgent as an ancient epic.",
    history: [
      "The painting tells the true story of Brook Watson, attacked by a shark in Havana Harbor in 1749. Watson survived, lost part of his leg and later became a British merchant and politician.",
      "Watson commissioned Copley to paint the rescue. The artist chose the moment before safety, with a boat hook raised and the shark circling for another attack.",
      "The central Black sailor holds a rope connecting the crew to Watson. His prominent role has prompted close study of the picture's links to Havana, maritime trade and the history of slavery.",
    ],
    lookFor: ["A triangle formed by Watson and the rescuers", "The rope linking the figures", "The uncertain anatomy of a shark Copley had never seen"],
    sources: [
      { label: "National Gallery of Art", href: "https://www.nga.gov/artworks/46471-watson-and-shark" },
      { label: "Wikipedia", href: wikipedia("Watson_and_the_Shark") },
      { label: "Public-domain image", href: commons("John Singleton Copley - Watson and the Shark - Google Art Project.jpg") },
    ],
  },
  {
    slug: "cafe-terrace-at-night-vincent-van-gogh",
    canvasId: "vincent-van-gogh-caf-terrace-at-night-1888",
    title: "Café Terrace at Night",
    artist: "Vincent van Gogh",
    artistYears: "1853-1890",
    year: "1888",
    movement: "Post-Impressionism",
    collection: "Kröller-Müller Museum, Otterlo",
    publicImage: commonsImage("Vincent van Gogh (1853-1890) Caféterras bij nacht (place du Forum) Kröller-Müller Museum Otterlo 23-8-2016 13-35-40.JPG", 1500),
    publicImageSource: commons("Vincent van Gogh (1853-1890) Caféterras bij nacht (place du Forum) Kröller-Müller Museum Otterlo 23-8-2016 13-35-40.JPG"),
    artistImage: portraits.vanGogh.image,
    artistImageSource: portraits.vanGogh.source,
    artistImageAlt: portraits.vanGogh.alt,
    summary: "A gas-lit café opens onto a deep blue street and starry sky. Van Gogh painted night without relying on black.",
    history: [
      "Van Gogh set up his easel in the Place du Forum in Arles and painted the scene on site. He described the yellow terrace and blue night in letters to his sister Willemien.",
      "The steep street narrows toward the center while tables and figures fill the foreground. Strong blue and yellow create light through contrast rather than smooth shading.",
      "This was van Gogh's first painted starry background. He made Starry Night Over the Rhône later that month and The Starry Night the following year.",
    ],
    lookFor: ["A night scene made with almost no black", "Stars placed above the receding street", "Warm gaslight reflected on cobblestones"],
    sources: [
      { label: "Kröller-Müller Museum", href: "https://www.krollermuller.nl/en/collection/vincent-van-gogh-terrace-of-a-caf-at-night-place-du-forum-km-108-565" },
      { label: "Wikipedia", href: wikipedia("Caf%C3%A9_Terrace_at_Night") },
      { label: "Public-domain image", href: commons("Vincent van Gogh (1853-1890) Caféterras bij nacht (place du Forum) Kröller-Müller Museum Otterlo 23-8-2016 13-35-40.JPG") },
    ],
  },
];

export function getArtHistoryEntry(slug: string): ArtHistoryEntry | undefined {
  return ART_HISTORY.find((entry) => entry.slug === slug);
}
