import {
  type ArtHistoryEntry,
  commons,
  commonsImage,
  portraits,
  wikipedia,
} from "./art-history-shared";

export const ART_HISTORY_PART_ONE: ArtHistoryEntry[] = [
  {
    slug: "the-starry-night-vincent-van-gogh",
    canvasId: "vincent-van-gogh-starry-night-1889",
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    artistYears: "1853-1890",
    year: "1889",
    movement: "Post-Impressionism",
    collection: "Museum of Modern Art, New York",
    publicImage: commonsImage("Van Gogh - Starry Night - Google Art Project.jpg", 1800),
    publicImageSource: commons("Van Gogh - Starry Night - Google Art Project.jpg"),
    artistImage: portraits.vanGogh.image,
    artistImageSource: portraits.vanGogh.source,
    artistImageAlt: portraits.vanGogh.alt,
    summary: "A quiet village sits beneath a sky that refuses to stay still. Van Gogh turned a view from Saint-Rémy into one of art's great night scenes.",
    history: [
      "Van Gogh painted this canvas while living at the asylum of Saint-Paul-de-Mausole in Saint-Rémy. The view began with the landscape outside his window. The village and its tall church came from memory and invention.",
      "The painting joined observation with a highly arranged sky. Thick strokes bend around stars, moon and cypress. Van Gogh later called the work an exaggeration, but its force comes from that deliberate push beyond a literal view.",
      "The work passed through the collections of Theo van Gogh and Jo van Gogh-Bonger. MoMA acquired it in 1941. It soon became the museum's best-known painting and a lasting symbol of van Gogh's final years.",
    ],
    lookFor: ["The cypress that links the ground and sky", "Concentric halos around each star", "The calm village beneath the moving heavens"],
    sources: [
      { label: "Museum of Modern Art", href: "https://www.moma.org/collection/works/79802" },
      { label: "Wikipedia", href: wikipedia("The_Starry_Night") },
      { label: "Public-domain image", href: commons("Van Gogh - Starry Night - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-great-wave-off-kanagawa-hokusai",
    canvasId: "katsushika-hokusai-the-great-wave-off-kanagawa-c-1830",
    title: "The Great Wave off Kanagawa",
    artist: "Katsushika Hokusai",
    artistYears: "1760-1849",
    year: "c. 1830-1832",
    movement: "Ukiyo-e",
    collection: "Impressions held by museums worldwide",
    publicImage: commonsImage("The Great Wave off Kanagawa.jpg", 1800),
    publicImageSource: commons("The Great Wave off Kanagawa.jpg"),
    artistImage: portraits.hokusai.image,
    artistImageSource: portraits.hokusai.source,
    artistImageAlt: portraits.hokusai.alt,
    summary: "Three boats face a cresting wall of water while Mount Fuji waits in the distance. Hokusai made danger, work and stillness share one small print.",
    history: [
      "The print opened Hokusai's series Thirty-six Views of Mount Fuji. It was made with carved woodblocks and printed in color. Many impressions were produced, which helped the image travel far beyond Japan.",
      "The wave dominates at first glance. Look again and Mount Fuji repeats its triangular shape in the distance. The fishermen lean into long boats built to carry fresh fish quickly across Edo Bay.",
      "Hokusai used imported Prussian blue, a strong new pigment in Japan. The print later reached Europe and fed the nineteenth-century taste for Japanese art. Its compact design still feels startlingly modern.",
    ],
    lookFor: ["Claw-like tips at the wave's crest", "Mount Fuji framed by the breaking water", "The rowers folded low inside the boats"],
    sources: [
      { label: "The Metropolitan Museum of Art", href: "https://www.metmuseum.org/art/collection/search/45434" },
      { label: "Wikipedia", href: wikipedia("The_Great_Wave_off_Kanagawa") },
      { label: "Public-domain image", href: commons("The Great Wave off Kanagawa.jpg") },
    ],
  },
  {
    slug: "girl-with-a-pearl-earring-johannes-vermeer",
    canvasId: "johannes-vermeer-the-girl-with-the-pearl-earring-c-1665",
    title: "Girl with a Pearl Earring",
    artist: "Johannes Vermeer",
    artistYears: "1632-1675",
    year: "c. 1665",
    movement: "Dutch Golden Age",
    collection: "Mauritshuis, The Hague",
    publicImage: commonsImage("Meisje met de parel.jpg", 1500),
    publicImageSource: commons("Meisje met de parel.jpg"),
    artistImage: portraits.vermeer.image,
    artistImageSource: portraits.vermeer.source,
    artistImageAlt: portraits.vermeer.alt,
    summary: "A young figure turns toward us against a dark field. One bright earring and a half-open mouth make the moment feel unfinished.",
    history: [
      "This is a tronie, not a formal portrait. Dutch artists used tronies to study a face, expression or unusual costume. The sitter's identity was never the point.",
      "Vermeer built the image from broad, clear shapes. The blue and yellow head covering feels exotic rather than documentary. The earring is only a few pale strokes, with no hard outline or visible hook.",
      "The painting entered the Mauritshuis in 1903 after a collector bought it at auction in 1881. Cleaning restored its cool color and direct gaze. Modern research has revealed eyelashes, a green curtain and tiny changes beneath the surface.",
    ],
    lookFor: ["The wet highlight at the corner of the mouth", "Soft edges where the face meets shadow", "The pearl suggested by light rather than detail"],
    sources: [
      { label: "Mauritshuis", href: "https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring" },
      { label: "Wikipedia", href: wikipedia("Girl_with_a_Pearl_Earring") },
      { label: "Public-domain image", href: commons("Meisje met de parel.jpg") },
    ],
  },
  {
    slug: "the-scream-edvard-munch",
    canvasId: "edvard-munch-the-scream-1893",
    title: "The Scream",
    artist: "Edvard Munch",
    artistYears: "1863-1944",
    year: "1893",
    movement: "Expressionism",
    collection: "National Museum, Oslo",
    publicImage: commonsImage("Edvard Munch - The Scream - Google Art Project.jpg", 1500),
    publicImageSource: commons("Edvard Munch - The Scream - Google Art Project.jpg"),
    artistImage: portraits.munch.image,
    artistImageSource: portraits.munch.source,
    artistImageAlt: portraits.munch.alt,
    summary: "A figure stops on a bridge while the landscape seems to cry with it. Munch painted an inner shock as if it had spread through the air.",
    history: [
      "Munch traced the image to a walk near Kristiania, now Oslo. He wrote of a blood-red sky and a great scream passing through nature. The scene became part of his wider Frieze of Life project.",
      "Several versions survive in paint, pastel and print. The National Museum's 1893 painting is the earliest painted version. Its cardboard support and mixed materials add to the raw, exposed effect.",
      "The bridge locks the composition into sharp perspective. Everything beyond it bends and ripples. The central figure is not clearly male or female, which helped it become a broad image of fear rather than one person's story.",
    ],
    lookFor: ["The straight bridge against the fluid landscape", "Two calm walkers in the distance", "Bands of color that echo sound waves"],
    sources: [
      { label: "National Museum of Norway", href: "https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939" },
      { label: "Wikipedia", href: wikipedia("The_Scream") },
      { label: "Public-domain image", href: commons("Edvard Munch - The Scream - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-birth-of-venus-sandro-botticelli",
    canvasId: "sandro-botticelli-the-birth-of-venus-c-1480",
    title: "The Birth of Venus",
    artist: "Sandro Botticelli",
    artistYears: "c. 1445-1510",
    year: "c. 1485",
    movement: "Early Renaissance",
    collection: "Uffizi Galleries, Florence",
    publicImage: commonsImage("Sandro Botticelli - La nascita di Venere - Google Art Project.jpg", 1800),
    publicImageSource: commons("Sandro Botticelli - La nascita di Venere - Google Art Project.jpg"),
    artistImage: portraits.botticelli.image,
    artistImageSource: portraits.botticelli.source,
    artistImageAlt: portraits.botticelli.alt,
    summary: "Venus reaches shore on a shell, pushed by wind and welcomed with a flowered cloak. Botticelli made an ancient myth feel weightless and new.",
    history: [
      "The scene shows Venus arriving on Cyprus after her birth from the sea. Zephyr blows from the left. A figure often identified as Spring waits on shore with a richly patterned mantle.",
      "Botticelli painted on canvas, still an unusual support for a large Florentine work. Gold touches once caught light in Venus's hair. The bodies favor elegant line over strict anatomy.",
      "The exact patron and original setting remain uncertain. The Medici circle and the poetry of Agnolo Poliziano shaped the world around the picture. By the nineteenth century, the work had become a defining image of Renaissance Florence.",
    ],
    lookFor: ["Roses carried on the wind", "The dark outline around each figure", "Tiny gold highlights in Venus's hair"],
    sources: [
      { label: "Uffizi Galleries", href: "https://www.uffizi.it/en/artworks/birth-of-venus" },
      { label: "Wikipedia", href: wikipedia("The_Birth_of_Venus") },
      { label: "Public-domain image", href: commons("Sandro Botticelli - La nascita di Venere - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-kiss-gustav-klimt",
    canvasId: "gustav-klimt-the-kiss-c-1907",
    title: "The Kiss",
    artist: "Gustav Klimt",
    artistYears: "1862-1918",
    year: "1908-1909",
    movement: "Vienna Secession",
    collection: "Upper Belvedere, Vienna",
    publicImage: commonsImage("The Kiss - Gustav Klimt - Google Cultural Institute.jpg", 1500),
    publicImageSource: commons("The Kiss - Gustav Klimt - Google Cultural Institute.jpg"),
    artistImage: portraits.klimt.image,
    artistImageSource: portraits.klimt.source,
    artistImageAlt: portraits.klimt.alt,
    summary: "Two figures meet inside a field of gold and pattern. Their bodies almost vanish into the decorated surface around them.",
    history: [
      "Klimt made The Kiss near the end of his golden phase. He had studied Byzantine mosaics in Ravenna and used gold leaf to collapse the space between painting, icon and ornament.",
      "The Belvedere bought the work in 1908 before Klimt had fully completed it. That quick purchase was a sharp change from the public battles that surrounded some of his earlier commissions.",
      "Squares and hard edges cover the man's robe. Circles and flowers soften the woman's dress. The couple kneels at the edge of a flowered ledge, which gives the embrace a quiet sense of risk.",
    ],
    lookFor: ["Gold leaf that changes with the light", "Different patterns assigned to each figure", "The narrow edge beneath the woman's feet"],
    sources: [
      { label: "Belvedere Museum", href: "https://www.belvedere.at/en/press/klimt-collection-belvedere" },
      { label: "Wikipedia", href: wikipedia("The_Kiss_(Klimt)") },
      { label: "Public-domain image", href: commons("The Kiss - Gustav Klimt - Google Cultural Institute.jpg") },
    ],
  },
  {
    slug: "water-lilies-claude-monet",
    canvasId: "claude-monet-water-lilies-1916",
    title: "Water Lilies",
    artist: "Claude Monet",
    artistYears: "1840-1926",
    year: "1916",
    movement: "Impressionism",
    collection: "One of Monet's late water-lily paintings",
    publicImage: commonsImage("Claude Monet - Water Lilies - Google Art Project.jpg", 1600),
    publicImageSource: commons("Claude Monet - Water Lilies - Google Art Project.jpg"),
    artistImage: portraits.monet.image,
    artistImageSource: portraits.monet.source,
    artistImageAlt: portraits.monet.alt,
    summary: "Monet removed the horizon and let a pond fill the whole canvas. Water, reflection and paint become hard to separate.",
    history: [
      "Monet created a water garden at Giverny and painted it for more than two decades. The pond was not a wild scene. He shaped it carefully with imported lilies, a bridge and controlled planting.",
      "His late canvases grew larger as his sight weakened and Europe went through war. Reflections break the normal sense of depth. A patch may read as water, cloud or bare paint depending on where you stand.",
      "The series ended in the great decorative panels now at the Musée de l'Orangerie. These works gave later abstract painters a model for large, immersive fields of color.",
    ],
    lookFor: ["Reflections with no visible horizon", "Thick flowers over thin pools of color", "Open passages where canvas nearly shows through"],
    sources: [
      { label: "Art Institute of Chicago", href: "https://www.artic.edu/artworks/16568/water-lilies" },
      { label: "Wikipedia", href: wikipedia("Water_Lilies_(Monet_series)") },
      { label: "Public-domain image", href: commons("Claude Monet - Water Lilies - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-creation-of-adam-michelangelo",
    canvasId: "michelangelo-the-creation-of-adam-1512",
    title: "The Creation of Adam",
    artist: "Michelangelo",
    artistYears: "1475-1564",
    year: "c. 1512",
    movement: "High Renaissance",
    collection: "Sistine Chapel, Vatican City",
    publicImage: commonsImage("Michelangelo - Creation of Adam (cropped).jpg", 1800),
    publicImageSource: commons("Michelangelo - Creation of Adam (cropped).jpg"),
    artistImage: portraits.michelangelo.image,
    artistImageSource: portraits.michelangelo.source,
    artistImageAlt: portraits.michelangelo.alt,
    summary: "Two hands almost touch. Michelangelo turned the creation of humanity into a gap charged with movement.",
    history: [
      "The fresco belongs to the central sequence on the Sistine Chapel ceiling. Michelangelo painted the vast ceiling between 1508 and 1512, working on wet plaster in sections.",
      "Adam rests heavily on the earth. God moves toward him inside a rushing group of figures and cloth. Their nearly touching fingers hold the instant before life passes between them.",
      "The image became famous far beyond its chapel setting. Restoration completed in 1994 removed centuries of soot and glue, revealing a much brighter range of pink, green and blue.",
    ],
    lookFor: ["The small charged space between two fingers", "Adam's body echoing God's pose", "The sweeping mantle that carries the heavenly group"],
    sources: [
      { label: "Vatican Museums", href: "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/cappella-sistina/volta/storie-centrali/creazione-di-adamo.html" },
      { label: "Wikipedia", href: wikipedia("The_Creation_of_Adam") },
      { label: "Public-domain image", href: commons("Michelangelo - Creation of Adam (cropped).jpg") },
    ],
  },
  {
    slug: "the-school-of-athens-raphael",
    canvasId: "raphael-the-school-of-athens-1509",
    title: "The School of Athens",
    artist: "Raphael",
    artistYears: "1483-1520",
    year: "1509-1511",
    movement: "High Renaissance",
    collection: "Apostolic Palace, Vatican City",
    publicImage: commonsImage("The School of Athens by Raffaello Sanzio da Urbino.jpg", 1800),
    publicImageSource: commons("The School of Athens by Raffaello Sanzio da Urbino.jpg"),
    artistImage: portraits.raphael.image,
    artistImageSource: portraits.raphael.source,
    artistImageAlt: portraits.raphael.alt,
    summary: "Ancient thinkers gather inside an ideal building. Raphael made philosophy look like a lively public event.",
    history: [
      "Pope Julius II asked Raphael to decorate rooms in the Vatican. This fresco faces a scene of theology, setting reason and faith in a carefully balanced program.",
      "Plato and Aristotle walk at the center. Plato points upward toward ideal forms. Aristotle extends his hand toward the material world. Around them, groups argue, calculate, read and listen.",
      "Raphael used single-point perspective to pull every line toward the central pair. He also gave several ancient figures the faces of Renaissance artists, including a brooding Michelangelo as Heraclitus.",
    ],
    lookFor: ["Perspective lines aimed at Plato and Aristotle", "Raphael's own face at the far right", "Michelangelo's features on the seated Heraclitus"],
    sources: [
      { label: "Vatican Museums", href: "https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/stanze-di-raffaello/stanza-della-segnatura/scuola-di-atene.html" },
      { label: "Wikipedia", href: wikipedia("The_School_of_Athens") },
      { label: "Public-domain image", href: commons("The School of Athens by Raffaello Sanzio da Urbino.jpg") },
    ],
  },
  {
    slug: "the-garden-of-earthly-delights-hieronymus-bosch",
    canvasId: "hieronymus-bosch-the-garden-of-earthly-delights",
    title: "The Garden of Earthly Delights",
    artist: "Hieronymus Bosch",
    artistYears: "c. 1450-1516",
    year: "c. 1490-1500",
    movement: "Northern Renaissance",
    collection: "Museo Nacional del Prado, Madrid",
    publicImage: commonsImage("The Garden of Earthly Delights by Bosch High Resolution.jpg", 1800),
    publicImageSource: commons("The Garden of Earthly Delights by Bosch High Resolution.jpg"),
    artistImage: portraits.bosch.image,
    artistImageSource: portraits.bosch.source,
    artistImageAlt: portraits.bosch.alt,
    summary: "Paradise, earthly pleasure and punishment unfold across three crowded panels. Bosch packed a moral puzzle with details that still resist a single answer.",
    history: [
      "The triptych moves from Eden on the left to a crowded central garden and a dark hell on the right. When closed, its outer panels show the world inside a transparent sphere.",
      "Bosch mixed familiar religious subjects with invented animals, giant fruit and impossible machines. The work was probably made for a courtly audience that could study and debate its strange details at close range.",
      "The painting entered the Spanish royal collection in the sixteenth century and later moved to the Prado. Its meaning remains disputed. Warning, satire and fascination all occupy the same surface.",
    ],
    lookFor: ["The owl hidden in the Eden panel", "Fragile fruit larger than people", "Musical instruments turned into tools of punishment"],
    sources: [
      { label: "Museo Nacional del Prado", href: "https://www.museodelprado.es/en/the-collection/art-work/the-garden-of-earthly-delights-triptych/02388242-6d6a-4e9e-a992-e1311eab3609" },
      { label: "Wikipedia", href: wikipedia("The_Garden_of_Earthly_Delights") },
      { label: "Public-domain image", href: commons("The Garden of Earthly Delights by Bosch High Resolution.jpg") },
    ],
  },
  {
    slug: "lady-with-an-ermine-leonardo-da-vinci",
    canvasId: "leonardo-da-vinci-the-lady-with-an-ermine-1489",
    title: "Lady with an Ermine",
    artist: "Leonardo da Vinci",
    artistYears: "1452-1519",
    year: "c. 1489-1490",
    movement: "High Renaissance",
    collection: "National Museum in Kraków",
    publicImage: commonsImage("Leonardo da Vinci - Lady with an Ermine - WGA12698.jpg", 1500),
    publicImageSource: commons("Leonardo da Vinci - Lady with an Ermine - WGA12698.jpg"),
    artistImage: portraits.leonardo.image,
    artistImageSource: portraits.leonardo.source,
    artistImageAlt: portraits.leonardo.alt,
    summary: "Cecilia Gallerani turns as if someone has just entered the room. The animal in her arms turns with her.",
    history: [
      "Leonardo painted Cecilia while working at the Milanese court of Ludovico Sforza. She was educated, wrote poetry and was Ludovico's young mistress.",
      "The ermine may carry several meanings. It was linked with purity, with Ludovico's emblem and with a play on Cecilia's surname. Leonardo joined the animal and sitter through matching turns and long, alert hands.",
      "The portrait was bought in Italy by Prince Adam Jerzy Czartoryski around 1800. It survived repeated wartime moves and Nazi seizure. It is now the only Leonardo painting in a Polish collection.",
    ],
    lookFor: ["The shared turn of sitter and animal", "Leonardo's careful study of the hand", "Soft light modeling the face against darkness"],
    sources: [
      { label: "National Museum in Kraków", href: "https://mnk.pl/en/collections/lady-with-an-ermine/" },
      { label: "Wikipedia", href: wikipedia("Lady_with_an_Ermine") },
      { label: "Public-domain image", href: commons("Leonardo da Vinci - Lady with an Ermine - WGA12698.jpg") },
    ],
  },
  {
    slug: "bacchus-and-ariadne-titian",
    canvasId: "titian-bacchus-and-ariadne-1522",
    title: "Bacchus and Ariadne",
    artist: "Titian",
    artistYears: "c. 1488-1576",
    year: "1520-1523",
    movement: "Venetian Renaissance",
    collection: "The National Gallery, London",
    publicImage: commonsImage("Titian - Bacchus and Ariadne - National Gallery, London.jpg", 1800),
    publicImageSource: commons("Titian - Bacchus and Ariadne - National Gallery, London.jpg"),
    artistImage: portraits.titian.image,
    artistImageSource: portraits.titian.source,
    artistImageAlt: portraits.titian.alt,
    summary: "Bacchus leaps from his chariot at the sight of Ariadne. Titian freezes love at first sight in a burst of blue, red and motion.",
    history: [
      "The painting was made for Alfonso I d'Este's private suite in Ferrara. It belonged to a series of mythological scenes designed for close, learned viewing.",
      "Ariadne has been abandoned by Theseus, whose ship appears at the far left. Bacchus arrives with a noisy group of followers and promises her a place among the stars.",
      "Titian used some of the strongest pigments then available. Ultramarine fills the sky. Bacchus's red drapery cuts across it while his body hangs in midair, an unusually bold pose for the period.",
    ],
    lookFor: ["Theseus's tiny ship leaving the island", "Ariadne's crown becoming a constellation", "The cheetahs pulling Bacchus's chariot"],
    sources: [
      { label: "The National Gallery", href: "https://www.nationalgallery.org.uk/paintings/titian-bacchus-and-ariadne" },
      { label: "Wikipedia", href: wikipedia("Bacchus_and_Ariadne") },
      { label: "Public-domain image", href: commons("Titian - Bacchus and Ariadne - National Gallery, London.jpg") },
    ],
  },

];
