import {
  type ArtHistoryEntry,
  commons,
  commonsImage,
  portraits,
  wikipedia,
} from "./art-history-shared";

export const ART_HISTORY_PART_TWO: ArtHistoryEntry[] = [
  {
    slug: "the-cardsharps-caravaggio",
    canvasId: "michelangelo-caravaggio-cardsharps-1594",
    title: "The Cardsharps",
    artist: "Caravaggio",
    artistYears: "1571-1610",
    year: "c. 1595",
    movement: "Baroque",
    collection: "Kimbell Art Museum, Fort Worth",
    publicImage: commonsImage("Michelangelo Caravaggio 060.jpg", 1700),
    publicImageSource: commons("Michelangelo Caravaggio 060.jpg"),
    artistImage: portraits.caravaggio.image,
    artistImageSource: portraits.caravaggio.source,
    artistImageAlt: portraits.caravaggio.alt,
    summary: "A well-dressed young player studies his cards while two cheats work around him. Caravaggio makes the trick obvious to us and invisible to its target.",
    history: [
      "Caravaggio painted this early in his Roman career. The scene helped establish his reputation and attracted the patronage of Cardinal Francesco Maria del Monte.",
      "The older cheat signals the victim's cards through a torn glove. His partner reaches behind his back for a hidden card. Every costume detail supports the deception.",
      "The Kimbell painting was rediscovered in 1987 after its authorship had been forgotten. Technical study and documentary evidence supported its acceptance as Caravaggio's original composition.",
    ],
    lookFor: ["The accomplice's split glove", "Extra cards tucked behind the young cheat", "The victim's open, unguarded posture"],
    sources: [
      { label: "Kimbell Art Museum", href: "https://kimbellart.org/collection/ap-198706" },
      { label: "Wikipedia", href: wikipedia("The_Cardsharps") },
      { label: "Public-domain image", href: commons("Michelangelo Caravaggio 060.jpg") },
    ],
  },
  {
    slug: "a-sunday-on-la-grande-jatte-georges-seurat",
    canvasId: "georges-seurat-a-sunday-afternoon-on-the-island-of-la-grande-jatte-c-1884",
    title: "A Sunday on La Grande Jatte",
    artist: "Georges Seurat",
    artistYears: "1859-1891",
    year: "1884-1886",
    movement: "Neo-Impressionism",
    collection: "Art Institute of Chicago",
    publicImage: commonsImage("Georges Seurat - A Sunday on La Grande Jatte -- 1884 - Google Art Project.jpg", 1800),
    publicImageSource: commons("Georges Seurat - A Sunday on La Grande Jatte -- 1884 - Google Art Project.jpg"),
    artistImage: portraits.seurat.image,
    artistImageSource: portraits.seurat.source,
    artistImageAlt: portraits.seurat.alt,
    summary: "Parisians gather beside the Seine, but no one quite touches. Seurat built a modern crowd from countless small marks and strict geometry.",
    history: [
      "Seurat worked on the ten-foot-wide canvas for about two years. He made many drawings and painted studies on the island before assembling the final scene in his studio.",
      "Small touches of contrasting color mix in the viewer's eye. The method became known as Pointillism, though Seurat preferred language that stressed color division and optical theory.",
      "The painting appeared at the final Impressionist exhibition in 1886 and pointed toward Neo-Impressionism. Its people are modern and fashionable, yet their stillness makes the sunny park feel formal and strange.",
    ],
    lookFor: ["The monkey on a lead at lower right", "A painted border that repeats the scene's colors", "Sails and umbrellas built from simple triangles"],
    sources: [
      { label: "Art Institute of Chicago", href: "https://www.artic.edu/artworks/27992/a-sunday-on-la-grande-jatte-1884" },
      { label: "Wikipedia", href: wikipedia("A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte") },
      { label: "Public-domain image", href: commons("Georges Seurat - A Sunday on La Grande Jatte -- 1884 - Google Art Project.jpg") },
    ],
  },
  {
    slug: "woman-with-a-parasol-claude-monet",
    canvasId: "claude-monet-lady-with-a-parasol-1875",
    title: "Woman with a Parasol",
    artist: "Claude Monet",
    artistYears: "1840-1926",
    year: "1875",
    movement: "Impressionism",
    collection: "National Gallery of Art, Washington",
    publicImage: commonsImage("Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg", 1500),
    publicImageSource: commons("Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg"),
    artistImage: portraits.monet.image,
    artistImageSource: portraits.monet.source,
    artistImageAlt: portraits.monet.alt,
    summary: "Camille Monet turns on a windy hill with her son behind her. Fast brushwork makes the air itself part of the portrait.",
    history: [
      "Monet painted his wife Camille and their son Jean outdoors at Argenteuil. The low viewpoint lifts Camille against the sky and gives a casual family walk unusual scale.",
      "The canvas was completed quickly, probably in one sitting. Exposed ground and loose strokes preserve that speed. The veil, grass and clouds all move in the same gust.",
      "Monet showed the painting at the second Impressionist exhibition in 1876. It joined a portrait-like figure with the movement and changing light that drove his landscape work.",
    ],
    lookFor: ["The green underside of the parasol", "A veil that almost dissolves into the sky", "Jean appearing just over the ridge"],
    sources: [
      { label: "National Gallery of Art", href: "https://www.nga.gov/artworks/61379-woman-parasol-madame-monet-and-her-son" },
      { label: "Wikipedia", href: wikipedia("Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son") },
      { label: "Public-domain image", href: commons("Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg") },
    ],
  },
  {
    slug: "luncheon-of-the-boating-party-renoir",
    canvasId: "renoir-luncheon-of-the-boating-party-1880-1881",
    title: "Luncheon of the Boating Party",
    artist: "Pierre-Auguste Renoir",
    artistYears: "1841-1919",
    year: "1880-1881",
    movement: "Impressionism",
    collection: "The Phillips Collection, Washington",
    publicImage: commonsImage("Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg", 1800),
    publicImageSource: commons("Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg"),
    artistImage: portraits.renoir.image,
    artistImageSource: portraits.renoir.source,
    artistImageAlt: portraits.renoir.alt,
    summary: "Friends linger over lunch on a balcony above the Seine. Renoir turned a social afternoon into a carefully revised monument to modern leisure.",
    history: [
      "The setting is the Maison Fournaise at Chatou, a restaurant popular with boaters. Renoir used friends, models and future wife Aline Charigot for the large group.",
      "The relaxed scene took months of planning and revision. Technical study shows that Renoir moved figures and added the striped awning after painting more of the open landscape.",
      "Collector Duncan Phillips bought the painting in 1923. It became the anchor of his young museum and remains the best-known work in the Phillips Collection.",
    ],
    lookFor: ["Aline Charigot playing with a small dog", "Gustave Caillebotte seated backward on a chair", "Red accents moving across hats, fruit and clothing"],
    sources: [
      { label: "The Phillips Collection", href: "https://www.phillipscollection.org/collection/luncheon-boating-party" },
      { label: "Wikipedia", href: wikipedia("Luncheon_of_the_Boating_Party") },
      { label: "Public-domain image", href: commons("Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg") },
    ],
  },
  {
    slug: "flaming-june-frederic-leighton",
    canvasId: "frederic-leighton-flaming-june-1895",
    title: "Flaming June",
    artist: "Frederic Leighton",
    artistYears: "1830-1896",
    year: "1895",
    movement: "Victorian Aestheticism",
    collection: "Museo de Arte de Ponce",
    publicImage: commonsImage("Frederic Leighton - Flaming June - Google Art Project.jpg", 1500),
    publicImageSource: commons("Frederic Leighton - Flaming June - Google Art Project.jpg"),
    artistImage: portraits.leighton.image,
    artistImageSource: portraits.leighton.source,
    artistImageAlt: portraits.leighton.alt,
    summary: "A sleeping figure curls into a near-perfect circle of orange cloth. Leighton made heat and stillness feel almost solid.",
    history: [
      "Leighton painted Flaming June near the end of his life. Its square format and tightly folded pose turn a resting woman into a study of line, color and enclosed form.",
      "The oleander at upper right may hint at danger because the plant is poisonous. The setting remains uncertain. It could be a terrace, a dream or a personification of summer itself.",
      "The painting disappeared from broad public view for decades. Luis A. Ferré bought it in 1963 for the museum he founded in Puerto Rico. Its reputation rose sharply after later exhibitions.",
    ],
    lookFor: ["The nearly circular body and drapery", "A narrow strip of bright sea", "The poisonous oleander branch"],
    sources: [
      { label: "Museo de Arte de Ponce", href: "https://emuseum.museoarteponce.org/objects/3669/flaming-june" },
      { label: "Wikipedia", href: wikipedia("Flaming_June") },
      { label: "Public-domain image", href: commons("Frederic Leighton - Flaming June - Google Art Project.jpg") },
    ],
  },
  {
    slug: "the-storm-on-the-sea-of-galilee-rembrandt",
    canvasId: "rembrandt-van-rijn-the-storm-on-the-sea-of-galilee-1633",
    title: "The Storm on the Sea of Galilee",
    artist: "Rembrandt van Rijn",
    artistYears: "1606-1669",
    year: "1633",
    movement: "Dutch Baroque",
    collection: "Isabella Stewart Gardner Museum, missing since 1990",
    publicImage: commonsImage("Rembrandt Christ in the Storm on the Lake of Galilee.jpg", 1500),
    publicImageSource: commons("Rembrandt Christ in the Storm on the Lake of Galilee.jpg"),
    artistImage: portraits.rembrandt.image,
    artistImageSource: portraits.rembrandt.source,
    artistImageAlt: portraits.rembrandt.alt,
    summary: "A small boat tilts into a wall of water while its passengers struggle in every direction. Calm sits at the center of the panic.",
    history: [
      "This is Rembrandt's only known painted seascape. He based it on the Gospel story in which Christ calms a storm as his disciples fear the boat will sink.",
      "A bright wave hits the left side while the right falls into shadow. Each figure reacts differently. One sailor looks out toward us and is often identified as Rembrandt himself.",
      "The painting was stolen from the Gardner Museum on March 18, 1990, with twelve other works. Its empty frame still hangs in the Dutch Room under the terms of Isabella Gardner's will.",
    ],
    lookFor: ["Rembrandt looking out from the boat", "The snapped rigging against bright spray", "Christ remaining calm in the shadows"],
    sources: [
      { label: "Isabella Stewart Gardner Museum", href: "https://www.gardnermuseum.org/experience/collection/10953" },
      { label: "Wikipedia", href: wikipedia("The_Storm_on_the_Sea_of_Galilee") },
      { label: "Public-domain image", href: commons("Rembrandt Christ in the Storm on the Lake of Galilee.jpg") },
    ],
  },
  {
    slug: "judith-beheading-holofernes-artemisia-gentileschi",
    canvasId: "artemisia-gentileschi-judith-beheading-holofernes-1620",
    title: "Judith Beheading Holofernes",
    artist: "Artemisia Gentileschi",
    artistYears: "1593-c. 1654",
    year: "c. 1620",
    movement: "Baroque",
    collection: "Uffizi Galleries, Florence",
    publicImage: commonsImage("Artemisia Gentileschi - Judith Beheading Holofernes - Google Art Project.jpg", 1600),
    publicImageSource: commons("Artemisia Gentileschi - Judith Beheading Holofernes - Google Art Project.jpg"),
    artistImage: portraits.gentileschi.image,
    artistImageSource: portraits.gentileschi.source,
    artistImageAlt: portraits.gentileschi.alt,
    summary: "Judith and her maid work together with physical force. Gentileschi pushed a familiar biblical scene close to the viewer and refused to soften it.",
    history: [
      "The story comes from the Book of Judith. Judith enters the enemy camp, gets the general Holofernes drunk and kills him to save her city.",
      "Gentileschi followed Caravaggio's dramatic light and close staging, but made Judith and Abra active partners. Their sleeves are rolled back. Their arms form a strong crossing structure over the bed.",
      "The painting was likely completed after Gentileschi returned to Rome from Florence. It entered the Medici collection and was later displayed at the Uffizi, where its authorship and force gained new attention in the twentieth century.",
    ],
    lookFor: ["The crossing diagonals of four arms", "Judith's carefully protected dress", "Light concentrated on the three faces"],
    sources: [
      { label: "Uffizi Galleries", href: "https://www.uffizi.it/en/artworks/judith-beheading-holofernes" },
      { label: "Wikipedia", href: wikipedia("Judith_Slaying_Holofernes_(Artemisia_Gentileschi,_Florence)") },
      { label: "Public-domain image", href: commons("Artemisia Gentileschi - Judith Beheading Holofernes - Google Art Project.jpg") },
    ],
  },
  {
    slug: "view-of-toledo-el-greco",
    canvasId: "el-greco-view-of-toledo-1600",
    title: "View of Toledo",
    artist: "El Greco",
    artistYears: "1541-1614",
    year: "c. 1599-1600",
    movement: "Spanish Renaissance",
    collection: "The Metropolitan Museum of Art, New York",
    publicImage: commonsImage("View of Toledo MET DT1502.jpg", 1500),
    publicImageSource: commons("View of Toledo MET DT1502.jpg"),
    artistImage: portraits.elGreco.image,
    artistImageSource: portraits.elGreco.source,
    artistImageAlt: portraits.elGreco.alt,
    summary: "Toledo rises beneath a green-black storm. El Greco rearranged the city to make a portrait of atmosphere rather than a street map.",
    history: [
      "Independent landscapes were rare in Spanish painting around 1600. El Greco made one of the period's most charged examples in the city where he had built his career.",
      "The skyline is recognizable but altered. El Greco shifted buildings to create a stronger rhythm and separated the cathedral from the Alcázar. Light breaks across the ground in irregular patches.",
      "The painting's long history before the nineteenth century is unclear. Modern artists and writers admired its stretched forms and emotional color, which seemed to anticipate Expressionism.",
    ],
    lookFor: ["Pale buildings under a nearly black cloud", "The city moved for visual effect", "Electric green cutting through the foreground"],
    sources: [
      { label: "The Metropolitan Museum of Art", href: "https://www.metmuseum.org/art/collection/search/436575" },
      { label: "Wikipedia", href: wikipedia("View_of_Toledo") },
      { label: "Public-domain image", href: commons("View of Toledo MET DT1502.jpg") },
    ],
  },
  {
    slug: "the-tortoise-trainer-osman-hamdi-bey",
    canvasId: "osman-hamdi-the-tortoise-trainer-1906",
    title: "The Tortoise Trainer",
    artist: "Osman Hamdi Bey",
    artistYears: "1842-1910",
    year: "1906",
    movement: "Ottoman Academic painting",
    collection: "Pera Museum, Istanbul",
    publicImage: commonsImage("The Tortoise Trainer - Osman Hamdi Bey.jpg", 1500),
    publicImageSource: commons("The Tortoise Trainer - Osman Hamdi Bey.jpg"),
    artistImage: portraits.osman.image,
    artistImageSource: portraits.osman.source,
    artistImageAlt: portraits.osman.alt,
    summary: "An elderly man bends toward a group of tortoises in a worn tiled room. The strange lesson has become a durable image of slow reform.",
    history: [
      "Osman Hamdi Bey was a painter, archaeologist and museum director. He often used himself as a model and built scenes from studied costumes, architecture and objects.",
      "The trainer carries a small drum and flute while the tortoises gather around leaves on the floor. The exact meaning is open, but the picture is often read as a satire on difficult, slow-moving institutions.",
      "The work appeared at the Paris Salon in 1906 under a French title meaning The Man with Tortoises. It is now one of the most recognized paintings in Turkey.",
    ],
    lookFor: ["Damaged tilework in the Green Mosque setting", "Musical instruments tucked behind the trainer", "Leaves used as both food and teaching aid"],
    sources: [
      { label: "Pera Museum", href: "https://www.peramuseum.org/artwork/the-tortoise-trainer/15/92" },
      { label: "Wikipedia", href: wikipedia("The_Tortoise_Trainer") },
      { label: "Public-domain image", href: commons("The Tortoise Trainer - Osman Hamdi Bey.jpg") },
    ],
  },
  {
    slug: "the-parasol-francisco-goya",
    canvasId: "francisco-goya-the-parasol-1777",
    title: "The Parasol",
    artist: "Francisco Goya",
    artistYears: "1746-1828",
    year: "1777",
    movement: "Rococo",
    collection: "Museo Nacional del Prado, Madrid",
    publicImage: commonsImage("El Quitasol (Goya).jpg", 1700),
    publicImageSource: commons("El Quitasol (Goya).jpg"),
    artistImage: portraits.goya.image,
    artistImageSource: portraits.goya.source,
    artistImageAlt: portraits.goya.alt,
    summary: "A young man shades a seated woman on a bright day. The scene looks casual, but it was designed for a royal dining room wall.",
    history: [
      "Goya made The Parasol as a full-size cartoon for a tapestry. The finished textile was intended for the dining room of the future Charles IV and María Luisa of Parma at El Pardo.",
      "The pair wear fashionable clothing associated with Madrid's majos and majas. A low viewpoint and strong diagonal parasol suit the painting's planned position high on a wall.",
      "The tapestry project gave Goya steady royal work and practice with scenes of modern life. Its easy charm sits far from the darker court pictures and war images he made later.",
    ],
    lookFor: ["The parasol making a strong green diagonal", "A small dog curled in the foreground", "Sunlight modeled for translation into wool and silk"],
    sources: [
      { label: "Museo Nacional del Prado", href: "https://www.museodelprado.es/en/the-collection/art-work/the-parasol/a230a80f-a899-4535-9e90-ad883bd096c5" },
      { label: "Wikipedia", href: wikipedia("The_Parasol") },
      { label: "Public-domain image", href: commons("El Quitasol (Goya).jpg") },
    ],
  },
  {
    slug: "watson-and-the-shark-john-singleton-copley",
    canvasId: "john-copley-watson-and-the-shark-1778",
    title: "Watson and the Shark",
    artist: "John Singleton Copley",
    artistYears: "1738-1815",
    year: "1778",
    movement: "History painting",
    collection: "National Gallery of Art, Washington",
    publicImage: commonsImage("John Singleton Copley - Watson and the Shark - Google Art Project.jpg", 1800),
    publicImageSource: commons("John Singleton Copley - Watson and the Shark - Google Art Project.jpg"),
    artistImage: portraits.copley.image,
    artistImageSource: portraits.copley.source,
    artistImageAlt: portraits.copley.alt,
    summary: "A rescue stalls at the most dangerous instant. Copley made a recent event look as grand and urgent as an ancient epic.",
    history: [
      "The painting tells the true story of Brook Watson, attacked by a shark in Havana Harbor in 1749. Watson survived, lost part of his leg and later became a British merchant and politician.",
      "Watson commissioned Copley to paint the rescue. The artist chose the moment before safety, with a boat hook raised and the shark circling for another attack.",
      "The central Black sailor holds a rope connecting the crew to Watson. His prominent role has prompted close study of the picture's links to Havana, maritime trade and the history of slavery.",
    ],
    lookFor: ["A triangle formed by Watson and the rescuers", "The rope linking the figures", "The uncertain anatomy of a shark Copley had never seen"],
    sources: [
      { label: "National Gallery of Art", href: "https://www.nga.gov/artworks/46471-watson-and-shark" },
      { label: "Wikipedia", href: wikipedia("Watson_and_the_Shark") },
      { label: "Public-domain image", href: commons("John Singleton Copley - Watson and the Shark - Google Art Project.jpg") },
    ],
  },
  {
    slug: "cafe-terrace-at-night-vincent-van-gogh",
    canvasId: "vincent-van-gogh-caf-terrace-at-night-1888",
    title: "Café Terrace at Night",
    artist: "Vincent van Gogh",
    artistYears: "1853-1890",
    year: "1888",
    movement: "Post-Impressionism",
    collection: "Kröller-Müller Museum, Otterlo",
    publicImage: commonsImage("Vincent van Gogh (1853-1890) Caféterras bij nacht (place du Forum) Kröller-Müller Museum Otterlo 23-8-2016 13-35-40.JPG", 1500),
    publicImageSource: commons("Vincent van Gogh (1853-1890) Caféterras bij nacht (place du Forum) Kröller-Müller Museum Otterlo 23-8-2016 13-35-40.JPG"),
    artistImage: portraits.vanGogh.image,
    artistImageSource: portraits.vanGogh.source,
    artistImageAlt: portraits.vanGogh.alt,
    summary: "A gas-lit café opens onto a deep blue street and starry sky. Van Gogh painted night without relying on black.",
    history: [
      "Van Gogh set up his easel in the Place du Forum in Arles and painted the scene on site. He described the yellow terrace and blue night in letters to his sister Willemien.",
      "The steep street narrows toward the center while tables and figures fill the foreground. Strong blue and yellow create light through contrast rather than smooth shading.",
      "This was van Gogh's first painted starry background. He made Starry Night Over the Rhône later that month and The Starry Night the following year.",
    ],
    lookFor: ["A night scene made with almost no black", "Stars placed above the receding street", "Warm gaslight reflected on cobblestones"],
    sources: [
      { label: "Kröller-Müller Museum", href: "https://www.krollermuller.nl/en/collection/vincent-van-gogh-terrace-of-a-caf-at-night-place-du-forum-km-108-565" },
      { label: "Wikipedia", href: wikipedia("Caf%C3%A9_Terrace_at_Night") },
      { label: "Public-domain image", href: commons("Vincent van Gogh (1853-1890) Caféterras bij nacht (place du Forum) Kröller-Müller Museum Otterlo 23-8-2016 13-35-40.JPG") },
    ],
  },
];


