CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  display_name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE games (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  state ENUM('LOBBY','ACTIVE','ENDED') NOT NULL,
  current_phase ENUM('LOBBY','MORNING','AFTERNOON','SELLING','ENDED') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE game_players (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  game_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  player_order INT NOT NULL,
  nutrition INT NOT NULL DEFAULT 5,
  score INT NOT NULL DEFAULT 0,
  is_connected BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (game_id) REFERENCES games(id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE KEY unique_game_player (game_id, user_id)
);

CREATE TABLE game_sessions (
  game_id VARCHAR(64) PRIMARY KEY,
  host_id VARCHAR(64) NOT NULL,
  phase ENUM('LOBBY','MORNING','AFTERNOON','SELLING','ENDED') NOT NULL DEFAULT 'LOBBY',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE game_session_players (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  session_id VARCHAR(64) NOT NULL,
  player_id VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  player_order INT NOT NULL,
  is_connected BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_session_player (session_id, player_id),
  FOREIGN KEY (session_id) REFERENCES game_sessions(game_id)
);

CREATE TABLE game_state_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  game_id BIGINT UNSIGNED NOT NULL,
  state_json JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (game_id) REFERENCES games(id)
);

CREATE TABLE canvases (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  artist VARCHAR(128),
  year VARCHAR(16),
  star_value INT NOT NULL,
  paint_value INT NOT NULL,
  food_value INT NOT NULL,
  layout_json JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
